services:
  db:
    image: mysql:8
    container_name: db
    restart: unless-stopped
    tty: true
    environment:
      MYSQL_DATABASE: defaultdb
      MYSQL_ROOT_PASSWORD: iYgHtGXY8gkbb3rxqpDl
      SERVICE_TAGS: dev
      SERVICE_NAME: mysql
    ports:
      - "3306:3306"
    volumes:
      - dbdata:/var/lib/mysql
    networks:
      - app-network

  app:
    build:
      context: './'
    ports:
      - '8000:8000'
    volumes:
      - .:/var/www/html
    networks:
      - app-network
    depends_on:
      - db

volumes:
  dbdata:
    driver: local

networks:
  app-network:
    driver: bridge

